### PR TITLE
Clean up path handling to fix routing bug, update tree

### LINKED ISSUE #31: Routing fails with root path.
```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/VividCortex/siesta"
)

func main() {
	// Create a new Service rooted at "/"
	service := siesta.NewService("/")

	// Route accepts normal http.Handlers.
	service.Route("GET", "/", "Sends 'Hello, world!'", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "Hello, world!")
	})

	// Let's create some simple middleware.
	// This one will accept a Context argument.
	timestamper := func(c siesta.Context, w http.ResponseWriter, r *http.Request) {
		c.Set("start", time.Now())
	}

	timeHandler := func(c siesta.Context, w http.ResponseWriter, r *http.Request) {
		delta := time.Now().Sub(c.Get("start").(time.Time))
		fmt.Fprintf(w, "That took %v.\n", delta)
	}

	// We can compose the two handlers together and add it as a new route.
	service.Route("GET", "/time", "Sends how long it took to send a message", siesta.Compose(timestamper, timeHandler))

	// service is an http.Handler, so we can pass it directly to ListenAndServe.
	log.Fatal(http.ListenAndServe(":8080", service))
}
```

```
$ curl localhost:8080
404 page not found
```

We should see "Hello, world!". It behaves properly if the "/" route is added after the "/time" route.

### PR DESCRIPTION
**Pull request by PreetamJinka**
Closes #31.

### CODE REVIEW

**Comment by PreetamJinka** [comment]
This isn't fixed yet. I have a feeling that this problem is actually rooted in the tree implementation...

**Comment by PreetamJinka** [comment]
This is simpler than I thought. Good to take a break from problems :).

The issue is with [this line](https://github.com/VividCortex/siesta/blob/5cfebb3778e4ef938e019e4a744af011439a6275/service.go#L93):
```go
r.URL.Path = strings.TrimRight(r.URL.Path, "/")
```

We need to add some more documentation on why that's there.
Documentation issue reference: https://github.com/VividCortex/siesta/issues/20.

**Comment by PreetamJinka** [comment]
@potocnyj, want to take a look at this?

**Comment by potocnyj** [comment]
LGTM

**Pull request merged**
